[auth]
# EXAMPLE CONFIGURATION - Copy this to .streamlit/secrets.toml and add your real credentials
# 
# For local testing:
redirect_uri = "http://localhost:8501/"
# 
# For production (Streamlit Cloud):
# redirect_uri = "https://your-app-name.streamlit.app/"

cookie_secret = "your-super-secret-cookie-key-change-this-in-production"

# Get these from Google Cloud Console > APIs & Services > Credentials
client_id = "YOUR_GOOGLE_CLIENT_ID_HERE.apps.googleusercontent.com"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET_HERE"

server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

# Forms Agent Configuration
[forms_agent]
service_account_path = "forms_agent/service-account-key.json"

# SETUP INSTRUCTIONS:
# 1. Go to Google Cloud Console (https://console.cloud.google.com/)
# 2. Create a new project or select existing one
# 3. Enable Google Forms API and Google Drive API
# 4. Go to "APIs & Services" > "Credentials"
# 5. Create "OAuth 2.0 Client ID" credentials
# 6. Add your redirect URIs:
#    - For local: http://localhost:8501/
#    - For production: https://your-app-name.streamlit.app/
# 7. Copy the client_id and client_secret to .streamlit/secrets.toml
# 8. Configure OAuth consent screen
# 9. Add test users if needed

# SECURITY NOTES:
# - Never commit real credentials to git
# - Always use .streamlit/secrets.toml for actual credentials
# - Keep this file as a template only 